face_parameters:
  upperFaceStrength: 1
  upperFaceSmoothing: 0.001
  lowerFaceStrength: 1.3
  lowerFaceSmoothing: 0.0023
  faceMaskLevel: 0.6
  faceMaskSoftness: 0.0085
  skinStrength: 1.1
  eyelidOpenOffset: 0.06
  lipOpenOffset: -0.03
blendshape_parameters:
  enable_clamping_bs_weight: false
  multipliers:
    EyeBlinkLeft: 1
    EyeLookDownLeft: 0
    EyeLookInLeft: 0
    EyeLookOutLeft: 0
    EyeLookUpLeft: 0
    EyeSquintLeft: 1
    EyeWideLeft: 1
    EyeBlinkRight: 1
    EyeLookDownRight: 0
    EyeLookInRight: 0
    EyeLookOutRight: 0
    EyeLookUpRight: 0
    EyeSquintRight: 1
    EyeWideRight: 1
    JawForward: 0.7
    JawLeft: 0.2
    JawRight: 0.2
    JawOpen: 1
    MouthClose: 0.2
    MouthFunnel: 1.2
    MouthPucker: 1.2
    MouthLeft: 0.2
    MouthRight: 0.2
    MouthSmileLeft: 0.8
    MouthSmileRight: 0.8
    MouthFrownLeft: 0.5
    MouthFrownRight: 0.5
    MouthDimpleLeft: 0.8
    MouthDimpleRight: 0.8
    MouthStretchLeft: 0.05
    MouthStretchRight: 0.05
    MouthRollLower: 0.8
    MouthRollUpper: 0.5
    MouthShrugLower: 0.9
    MouthShrugUpper: 0.4
    MouthPressLeft: 0.8
    MouthPressRight: 0.8
    MouthLowerDownLeft: 0.8
    MouthLowerDownRight: 0.8
    MouthUpperUpLeft: 0.8
    MouthUpperUpRight: 0.8
    BrowDownLeft: 1
    BrowDownRight: 1
    BrowInnerUp: 1
    BrowOuterUpLeft: 1
    BrowOuterUpRight: 1
    CheekPuff: 0.2
    CheekSquintLeft: 1
    CheekSquintRight: 1
    NoseSneerLeft: 0.8
    NoseSneerRight: 0.8
    TongueOut: 0
  offsets:
    EyeBlinkLeft: 0
    EyeLookDownLeft: 0
    EyeLookInLeft: 0
    EyeLookOutLeft: 0
    EyeLookUpLeft: 0
    EyeSquintLeft: 0
    EyeWideLeft: 0
    EyeBlinkRight: 0
    EyeLookDownRight: 0
    EyeLookInRight: 0
    EyeLookOutRight: 0
    EyeLookUpRight: 0
    EyeSquintRight: 0
    EyeWideRight: 0
    JawForward: 0
    JawLeft: 0
    JawRight: 0
    JawOpen: 0
    MouthClose: 0
    MouthFunnel: 0
    MouthPucker: 0
    MouthLeft: 0
    MouthRight: 0
    MouthSmileLeft: 0
    MouthSmileRight: 0
    MouthFrownLeft: 0
    MouthFrownRight: 0
    MouthDimpleLeft: 0
    MouthDimpleRight: 0
    MouthStretchLeft: 0
    MouthStretchRight: 0
    MouthRollLower: 0
    MouthRollUpper: 0
    MouthShrugLower: 0
    MouthShrugUpper: 0
    MouthPressLeft: 0
    MouthPressRight: 0
    MouthLowerDownLeft: 0
    MouthLowerDownRight: 0
    MouthUpperUpLeft: 0
    MouthUpperUpRight: 0
    BrowDownLeft: 0
    BrowDownRight: 0
    BrowInnerUp: 0
    BrowOuterUpLeft: 0
    BrowOuterUpRight: 0
    CheekPuff: 0
    CheekSquintLeft: 0
    CheekSquintRight: 0
    NoseSneerLeft: 0
    NoseSneerRight: 0
    TongueOut: 0
live_transition_time: 0.0001
beginning_emotion:
  amazement: 1
  anger: 0
  disgust: 0
  fear: 1
  outofbreath: 0
  pain: 1
  sadness: 0
post_processing_parameters:
  emotion_contrast: 1
  live_blend_coef: 0.7
  enable_preferred_emotion: false
  preferred_emotion_strength: 0.5
  emotion_strength: 0.6
  max_emotions: 3
emotion_with_timecode_list:
  emotion_with_timecode1:
    time_code: 0
    emotions:
      amazement: 0
      anger: 0
      cheekiness: 0
      disgust: 0
      fear: 0
      grief: 0
      joy: 1
      outofbreath: 0
      pain: 0
      sadness: 0
  emotion_with_timecode2:
    time_code: 1
    emotions:
      amazement: 0
      anger: 0
      cheekiness: 0
      disgust: 0
      fear: 1
      grief: 0
      joy: 0
      outofbreath: 0
      pain: 0.1
      sadness: 0
emotion:
  happiness: 0.5
  anger: 1
  sadness: 0
  surprise: 0
  disgust: 0
  fear: 0
  neutral: 0.5
audio2face:
  jawOpen: 0.5
  mouthShape: 0.5
  lipSyncIntensity: 0.5
blendshapes:
  browInnerUp: 0
  browDownLeft: 0
  browDownRight: 0
  browOuterUpLeft: 0
  browOuterUpRight: 0
  eyeLookUpLeft: 0
  eyeLookUpRight: 0
  eyeLookDownLeft: 0
  eyeLookDownRight: 0
  eyeLookInLeft: 0
  eyeLookInRight: 0
  eyeLookOutLeft: 0
  eyeLookOutRight: 0
  eyeBlinkLeft: 0
  eyeBlinkRight: 0
  eyeSquintLeft: 0
  eyeSquintRight: 0
  eyeWideLeft: 0
  eyeWideRight: 0
  cheekPuff: 0
  cheekSquintLeft: 0
  cheekSquintRight: 0
  noseSneerLeft: 0
  noseSneerRight: 0
  mouthFunnel: 0
  mouthPucker: 0
  mouthLeft: 0
  mouthRight: 0
  mouthRollUpper: 0
  mouthRollLower: 0
  mouthShrugUpper: 0
  mouthShrugLower: 0
  mouthClose: 0
  mouthSmileLeft: 0
  mouthSmileRight: 0
  mouthFrownLeft: 0
  mouthFrownRight: 0
  mouthDimpleLeft: 0
  mouthDimpleRight: 0
  mouthStretchLeft: 0
  mouthStretchRight: 0
  mouthPressLeft: 0
  mouthPressRight: 0
  mouthUpperUpLeft: 0
  mouthUpperUpRight: 0
  mouthLowerDownLeft: 0
  mouthLowerDownRight: 0
  mouthOpen: 0
  mouthTongueOut: 0
  jawForward: 0
  jawLeft: 0
  jawRight: 0
